"""add cached column to jobs

Revision ID: ab3d1bcf2303
Revises: 051612332459
Create Date: 2026-07-12 14:51:03.224298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3d1bcf2303'
down_revision: Union[str, Sequence[str], None] = '051612332459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows — a plain NOT NULL ADD COLUMN
    # fails outright against a populated table (ORM-level default=False
    # only applies to future inserts, not rows that already exist).
    op.add_column(
        "jobs",
        sa.Column("cached", sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'cached')
    # ### end Alembic commands ###
